"""empty message

Revision ID: c59a21356d9c
Revises: 39f7040c34ce
Create Date: 2019-10-31 18:00:24.659244

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c59a21356d9c'
down_revision = '39f7040c34ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('create_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'create_time')
    # ### end Alembic commands ###
